public/package.json

Update to latest steal for directories.lib fix

---

config/default.json
config/production.json
src/services/authentication/index.js
src/services/client_project/client_project-model.js
src/services/client_project/index.js
src/services/contribution_month/contribution_month-model.js
src/services/contributor/contributor-model.js
src/services/contributor/index.js
src/services/os_project/index.js
src/services/user/index.js
test/services/client_project/index.test.js
test/services/contributor/index.test.js
test/services/os_project/index.test.js
test/services/user/index.test.js

changed schema models to match wiki

cleanup and update models

---

config/production.json
src/index.js

fixes heroku mlab hosted mongodb error

updates for mlab settings

---

.travis.yml

heroku only, firebase to be added

update travis.yml for ci

---

.travis.yml

7 heroku deploy

---

public/components/contribution-month/contribution-month.js
public/components/select-contribution-month/select-contribution-month.js
public/components/select-contribution-month/select-contribution-month_test.js

Closes https://github.com/donejs/bitcentive/issues/57.

fixing issue with contribution month being retrieved with id __new__

---

src/services/contribution_month/contribution_month-model.js

Fixes client OS project schema

---

public/components/auth/auth.stache
public/components/register/register.js

Enables auto login after registeration

Auth fixes

---

public/models/contributor.js
public/package.json

Added set import and changed Feathers version

---

config/default.json
package.json
public/app.js
public/components/page-auth/page-auth.stache
public/package.json
src/app.js
src/services/authentication/index.js
src/services/client_project/hooks/index.js
src/services/client_project/index.js
src/services/contribution/hooks/index.js
src/services/contribution/index.js
src/services/contribution_month/hooks/index.js
src/services/contribution_month/index.js
src/services/contributor/hooks/index.js
src/services/contributor/index.js
src/services/os_project/hooks/index.js
src/services/os_project/index.js
src/services/user/hooks/index.js
src/services/user/hooks/prepare-github-user.js
src/services/user/index.js
src/services/user/user-model.js

This allows Github auth and makes it work through a popup window.  Need to get the popup window to close on success, still, but this at least allows login.

Get Github auth working

---

.travis.yml

Continuous Deployment

---

.travis.yml
public/package.json

Add credentials to firebase deploy command

---

config/custom-environment-variables.json

Trying out CD

---

.travis.yml

fix(Continuous Deployment): fix directory move before deployment

---

config/custom-environment-variables.json

Seriously...   this is getting ridiculous. Hopefully this works

fix(Continuous Deployment): fix connection to mongodb

---

.travis.yml
config/custom-environment-variables.json
config/production.json
package.json
public/.firebaserc
public/components/page-auth/page-auth.js
public/firebase.json
public/models/feathers.js
public/models/session.js
public/package.json
src/services/authentication/index.js

Merging to master, just to ensure CD is working now

Testing out CD

---

.travis.yml
config/custom-environment-variables.json
config/production.json
package.json
public/.firebaserc
public/components/page-auth/page-auth.js
public/firebase.json
public/models/feathers.js
public/models/session.js
public/package.json
src/services/authentication/index.js

Partially #113 but need to get access to heroku app to finsih it off
This should allow for every PR accepted to master, will trigger a deployment to production
Will push static assets to firebase hosting and use production configuration

Get Continuous Delivery Working

---

public/app.js

Closes #55. Github auth is working. The only thing I added was a redirect to the dashboard page whenever a session, otherwise users would remain on the login screen.
I also created another issue whereby sessions are not validated against Github, which is something we should be doing on initial page load IMO.

Github auth appears to be working (#55)

---

config/custom-environment-variables.json

This will *hopefully* fix the problem we are having with GitHub login in production

Fix Production GitHub Login

---

public/components/select-contribution-month/select-contribution-month.js

This fix removed all Monthly contributions before creating a new contribution month. #77

Remove all previous contributions before creating a new month

---

public/components/auth/auth.js
public/components/contribution-month/contribution-month.js
public/components/contributions/contributions.js
public/components/login/login.js
public/components/os-projects/os-projects.js
public/components/page-dashboard/page-dashboard.js
public/components/page-home/page-home.js
public/components/register/register.js
public/components/select-contribution-month/select-contribution-month.js

Part of #134 
This just changes the components in `Bitcentive` to use the new `view` over `template`

Use Component.view rather than deprecated Component.template

---

public/components/select-contribution-month/select-contribution-month.js
public/models/contribution-month/contribution-month.js

`addNewMonthlyOSProject` and `removeMonthlyOSProject` were duplicated and causing the issue. #135

135 delete osproject

---

public/components/os-projects/os-projects.js
public/components/os-projects/os-projects.stache
public/models/contribution-month/contribution-month.js

Covers parts of #136 that do not deal with the Monthly* maps in contribution month

code style changes and removing duplicate methods

---

public/package.json

Steals new RC requires explicit listing of the plugins, and I updated any steal related deps while I was at it

Updating steal and steal plugins

---

public/components/client-projects/client-projects.stache
public/components/os-projects/os-projects.stache
public/components/payouts/payouts.stache

Round and right-align the totals.

---

src/services/client_project/index.js
src/services/contribution/index.js
src/services/contribution_month/index.js
src/services/contributor/index.js
src/services/os_project/index.js
src/services/user/index.js

```js
paginate: {
default: 40,
max: 200
}
```
Fixes https://github.com/donejs/bitcentive/issues/182

Remove pagination defaults

---

src/app.js

Closes https://github.com/donejs/bitcentive/issues/186

Redirect to HTTPS

---

public/models/contribution-month/contribution-month.js

Closes #213 - Get's tests passing for staging.

Fix issue with merging contributions during update

---

public/components/payouts/payouts.less
public/components/payouts/payouts.stache

Fix payouts table overflow issue

---

public/components/select-contribution-month/select-contribution-month.js
public/lib/behaviors/smart-merge.js
public/lib/super-model.js
public/models/contribution-month/contribution-month.js
public/models/contribution-month/monthly-client-project.js
public/models/contribution-month/monthly-client-projects-os-project-list.js
public/models/contribution-month/monthly-contributions.js
public/models/contribution-month/monthly-os-project.js
public/models/os-project.js
public/package.json

integrated smartMerge into super model as a behavior #193

---

public/components/alerts/alerts.js
public/components/main-nav/main-nav.js
public/components/os-projects/os-projects.html
public/components/os-projects/os-projects.less
public/components/os-projects/os-projects.stache
public/components/page-contributors/page-contributors.js
public/components/page-dashboard/page-dashboard.js
public/components/payouts/payouts.js

Minor updates not related to any single particular issue

---

public/components/contribution-month/contribution-month.js
public/components/contribution-month/contribution-month.less
public/components/contribution-month/contribution-month.stache
public/models/contribution-month/contribution-month.js
public/models/contribution-month/test/contribution-month_test.js
src/services/contribution_month/contribution_month-model.js

Add startRate and endRate to ContributionMonth.

---

public/components/contributors/contributors.stache
public/components/model-edit-property/demo-fixture.js
public/components/model-edit-property/model-edit-property.html
public/components/model-edit-property/model-edit-property.js
public/components/model-edit-property/model-edit-property.less
public/components/model-edit-property/model-edit-property.md
public/components/model-edit-property/model-edit-property.stache
public/components/model-edit-property/model-edit-property_test.js
public/components/model-edit-property/test.html
public/test/test.js

Resolves #222
v2.1 demo
v2 demo.
v1.

#222 Make contributor name and email address editable.

---

public/components/client-projects/client-projects.stache
public/components/os-projects/os-projects.stache
public/models/contribution-month/contribution-month.js
public/models/contribution-month/test/contribution-month_test.js

Add sorting for os projects and client projects

---

README.md
database.json
migrate.js
migrations/20170109181647-start-rate-end-rate-fields.js
migrations/README.md
package.json

This needs to be tested in PROD.
Closes #232

Add db-migrate tool and document basic migration strategy

---

public/models/user.js

#202 user model: use shorthand types

---

public/components/contribution-month/contribution-month.js

#210 using shorthand getter

---

public/components/payouts/payouts.js
public/components/payouts/payouts.stache

Resolves #217
No Payouts:
Payouts:

#217 Hide payouts table when it's empty.

---

public/components/payouts/payouts.js
public/components/payouts/payouts.stache
public/components/payouts/payouts_test.js
public/models/contribution-month/contribution-month.js

#238 When calculating payouts, take all previous months into account.

---

public/components/alerts/alerts.html
public/components/client-projects/client-projects.html
public/components/contribution-month/contribution-month.html
public/components/contributions/contributions.html
public/components/contributors/contributors.html
public/components/main-nav/main-nav.html
public/components/model-edit-property/model-edit-property.html
public/components/os-projects/os-projects.html
public/components/page-contributors/page-contributors.html
public/components/page-dashboard/page-dashboard.html
public/components/page-home/page-home.html
public/components/payouts/payouts.html
public/components/payouts/payouts.less
public/components/select-contribution-month/select-contribution-month.html

Closes #244 
I changed spaces to tabs - sorry for the large diff.

Test and update all demo pages, minor fixes along the way

---

public/components/contribution-month/contribution-month.js
public/package.json

Requires can-connect PR https://github.com/canjs/can-connect/pull/248

fixed unnecessary ref requests #253

---

migrations/README.md

Trying to use DATABASE_URL to configure connection string on Heroku...

deploy with DATABASE_URL

---

database.json
migrate.js
migrations/20170109220001-add-user-isAdmin.js

Also, moved node_env from config to script.

db-migrate: added a new migration for isAdmin that uses updateMany

---

public/build.js
public/components/client-projects/client-projects_test.js
public/components/contribution-month/contribution-month_test.js
public/components/contributions/contributions_test.js
public/components/contributors/contributors_test.js
public/components/payouts/payouts_test.js
public/models/test.js
public/package.json
public/test/test.js

Also disabled debug for the build.

upgraded to latest can-connect which fixes smart-merge bug

---

public/components/page-dashboard/select-contribution-month/select-contribution-month.js
src/services/contribution_month/hooks/validate-request-data.js

Issue https://github.com/donejs/bitcentive/issues/300

work with UTC dates #300

---

public/components/page-dashboard/contributions/contributions.stache
public/components/ui/model-edit-property/demo-fixture.js
public/components/ui/model-edit-property/model-edit-property.html
public/components/ui/model-edit-property/model-edit-property.js
public/components/ui/model-edit-property/model-edit-property.less
public/components/ui/model-edit-property/model-edit-property.stache
public/components/ui/model-edit-property/model-edit-property_test.js
public/lib/stache-helpers/and.js
public/lib/stache-helpers/stache-helpers.js

Doubt: not sure whether `isAdmin()` should be used inside widget's template or passed from outside.

use editor widget for contributions #269

---

.travis.yml
public/models/session.js

seal session model #200

---

migrations/20170613191245-contribution-month-contributors.js
public/components/page-dashboard/contributions/contributions.js
public/components/page-dashboard/contributions/contributions.stache
public/components/page-dashboard/os-projects/os-projects.stache
public/components/page-dashboard/payouts/payouts.js
public/components/page-dashboard/payouts/payouts.less
public/components/page-dashboard/payouts/payouts.stache
public/components/page-dashboard/payouts/payouts_test.js
public/models/contribution-month/contribution-month.js
public/models/contribution-month/monthly-contributor.js
public/models/contribution-month/test/contribution-month-list_test.js
public/models/fixtures/contribution-months.json
src/services/contribution_month/contribution_month-model.js

fixes #247
fixes #304
fixes #274

Payouts Rewrite

---

public/build.js
public/development.html
public/package.json
public/production.html

hey @imaustink if you have some time today, I'd like your help testing the application with the optimized build output.
It seems ok to me, but a lot of options are disabled, I'm guessing it has to do with my user role in the app.

Setting up steal-tools optimized build

---

public/package.json

This is a hot fix to work around a bug breaking serialization

Revert can-define

---

public/build.js
public/development.html
public/package.json
public/production.html

This reverts commit 770bf7ceac2b5d8a2508d57ad4da08befbabc6b2, reversing
changes made to 9e91f091752d5e0411e74b636514a3b2a76b5904.

Revert "Merge pull request #338 from donejs/optimize"
